title: "Ivan Caballos"
description: "Graduate Electronics Engineer | Circuit Design (Analog) | Embedded Systems | Laser/Photonics Electronics"

remote_theme: lewismiddleton/cayman-dark
plugins:
  - jekyll-remote-theme
